require('dotenv').config();
const mongoose = require('mongoose');
const Event = require('./models/Event');

const events = [
  {
    title: "Christie's Important Watches",
    description: "Important Watches auction featuring rare Patek Philippe timepieces",
    category: "auctions",
    subcategory: "Watches",
    startDate: new Date("2026-06-12"),
    location: { city: "New York", country: "USA", venue: "Rockefeller Center" },
    pricing: { currency: "USD", displayPrice: "Est. $800K-$1.6M" },
    ticketUrl: "https://christies.com/en/auction/important-watches-26076",
    officialUrl: "https://christies.com/en/auction/important-watches-26076",
    tier: "premium",
    tags: ["Watches", "Patek Philippe", "Luxury"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Sotheby's High Jewelry",
    description: "High Jewelry auction featuring Cartier and rare diamonds",
    category: "auctions",
    subcategory: "Jewelry",
    startDate: new Date("2026-09-17"),
    location: { city: "Hong Kong", country: "China", venue: "Sotheby's Hong Kong" },
    pricing: { currency: "USD", displayPrice: "Est. $2M+" },
    ticketUrl: "https://sothebys.com/en/auctions/high-jewelry",
    officialUrl: "https://sothebys.com/en/auctions/high-jewelry",
    tier: "premium",
    tags: ["Jewelry", "Cartier", "Diamonds"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Monaco Grand Prix 2026",
    description: "Formula 1 Monaco Grand Prix with VIP yacht viewing experience",
    category: "sports",
    subcategory: "F1",
    startDate: new Date("2026-06-05"),
    endDate: new Date("2026-06-07"),
    location: { city: "Monte Carlo", country: "Monaco", venue: "Circuit de Monaco" },
    pricing: { currency: "EUR", displayPrice: "EUR 4,000+" },
    ticketUrl: "https://monaco-grandprix.com",
    officialUrl: "https://monaco-grandprix.com",
    tier: "premium",
    tags: ["F1", "Yacht Viewing", "Motorsport"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Wimbledon Championships",
    description: "The Championships, Wimbledon - Debenture tickets with hospitality",
    category: "sports",
    subcategory: "Tennis",
    startDate: new Date("2026-06-29"),
    endDate: new Date("2026-07-12"),
    location: { city: "London", country: "UK", venue: "All England Club" },
    pricing: { currency: "GBP", displayPrice: "GBP 3,395pp" },
    ticketUrl: "https://eventsinternational.co.uk/wimbledon",
    officialUrl: "https://wimbledon.com",
    tier: "premium",
    tags: ["Tennis", "Debenture", "Grand Slam"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Monaco Yacht Show 2026",
    description: "The world's leading superyacht show at Port Hercule",
    category: "yachts",
    subcategory: "Superyachts",
    startDate: new Date("2026-09-23"),
    endDate: new Date("2026-09-26"),
    location: { city: "Monte Carlo", country: "Monaco", venue: "Port Hercule" },
    pricing: { currency: "EUR", displayPrice: "EUR 400-EUR 2,070" },
    ticketUrl: "https://monacoyachtshow.com",
    officialUrl: "https://monacoyachtshow.com",
    tier: "premium",
    tags: ["Superyachts", "VIP", "Maritime"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "RM Sotheby's Monterey",
    description: "Monterey Car Week auction featuring Ferrari and classic cars",
    category: "auctions",
    subcategory: "Cars",
    startDate: new Date("2026-08-14"),
    location: { city: "Monterey", country: "USA", venue: "Monterey Conference Center" },
    pricing: { currency: "USD", displayPrice: "Est. $5M+" },
    ticketUrl: "https://rmsothebys.com",
    officialUrl: "https://rmsothebys.com",
    tier: "premium",
    tags: ["Cars", "Ferrari", "Classic"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Polo Gold Cup",
    description: "Snow Polo World Cup St. Moritz",
    category: "sports",
    subcategory: "Polo",
    startDate: new Date("2026-07-18"),
    endDate: new Date("2026-07-24"),
    location: { city: "St. Moritz", country: "Switzerland", venue: "Frozen Lake" },
    pricing: { currency: "CHF", displayPrice: "CHF 2,500+" },
    ticketUrl: "#",
    officialUrl: "https://snowpolo-stmoritz.com",
    tier: "premium",
    tags: ["Polo", "Snow", "Luxury"],
    isActive: true,
    isFeatured: false
  },
  {
    title: "Sotheby's Contemporary Evening HK",
    description: "Contemporary Art Evening Auction in Hong Kong",
    category: "auctions",
    subcategory: "Art",
    startDate: new Date("2026-09-29"),
    location: { city: "Hong Kong", country: "China", venue: "Sotheby's Hong Kong" },
    pricing: { currency: "USD", displayPrice: "Est. $10M+" },
    ticketUrl: "https://sothebys.com",
    officialUrl: "https://sothebys.com",
    tier: "premium",
    tags: ["Art", "Contemporary", "Auction"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Art Basel Miami Beach",
    description: "Premier international art fair in Miami",
    category: "arts",
    subcategory: "Art Fair",
    startDate: new Date("2026-12-03"),
    endDate: new Date("2026-12-06"),
    location: { city: "Miami", country: "USA", venue: "Miami Beach Convention Center" },
    pricing: { currency: "USD", displayPrice: "$75-$500" },
    ticketUrl: "https://artbasel.com",
    officialUrl: "https://artbasel.com",
    tier: "free",
    tags: ["Art", "Contemporary", "Fair"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Dubai World Cup",
    description: "World's richest horse race",
    category: "sports",
    subcategory: "Horse Racing",
    startDate: new Date("2027-03-28"),
    location: { city: "Dubai", country: "UAE", venue: "Meydan Racecourse" },
    pricing: { currency: "AED", displayPrice: "AED 2,500+" },
    ticketUrl: "#",
    officialUrl: "https://dubaiworldcup.com",
    tier: "premium",
    tags: ["Horse Racing", "VIP", "Dubai"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Cannes Film Festival",
    description: "Festival de Cannes - VIP access and premieres",
    category: "experiences",
    subcategory: "Film",
    startDate: new Date("2027-05-12"),
    endDate: new Date("2027-05-23"),
    location: { city: "Cannes", country: "France", venue: "Palais des Festivals" },
    pricing: { currency: "EUR", displayPrice: "EUR 3,000+" },
    ticketUrl: "#",
    officialUrl: "https://festival-cannes.com",
    tier: "premium",
    tags: ["Film", "VIP", "Cannes"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Singapore Yacht Show",
    description: "Asia's premier yacht show",
    category: "yachts",
    subcategory: "Superyachts",
    startDate: new Date("2027-04-23"),
    endDate: new Date("2027-04-26"),
    location: { city: "Singapore", country: "Singapore", venue: "Sentosa Cove" },
    pricing: { currency: "SGD", displayPrice: "S$500+" },
    ticketUrl: "#",
    officialUrl: "https://singaporeyachtshow.com",
    tier: "premium",
    tags: ["Superyachts", "Asia", "Maritime"],
    isActive: true,
    isFeatured: false
  },
  {
    title: "Bonhams Bond Street Jewels",
    description: "Fine jewelry auction at Bonhams London",
    category: "auctions",
    subcategory: "Jewelry",
    startDate: new Date("2027-03-15"),
    location: { city: "London", country: "UK", venue: "Bonhams Bond Street" },
    pricing: { currency: "GBP", displayPrice: "Est. £800K+" },
    ticketUrl: "https://bonhams.com",
    officialUrl: "https://bonhams.com",
    tier: "premium",
    tags: ["Jewelry", "Bonhams", "Luxury"],
    isActive: true,
    isFeatured: false
  },
  {
    title: "Bonhams Quail Lodge Auction",
    description: "Classic car auction at Quail Lodge",
    category: "auctions",
    subcategory: "Cars",
    startDate: new Date("2026-08-14"),
    location: { city: "Carmel Valley", country: "USA", venue: "Quail Lodge" },
    pricing: { currency: "USD", displayPrice: "Est. $12M+" },
    ticketUrl: "https://bonhams.com/quail-lodge",
    officialUrl: "https://bonhams.com/quail-lodge",
    tier: "premium",
    tags: ["Cars", "Bonhams", "Classic"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Phillips New York Watch Auction XI",
    description: "Important watches auction in New York",
    category: "auctions",
    subcategory: "Watches",
    startDate: new Date("2026-06-07"),
    location: { city: "New York", country: "USA", venue: "Phillips New York" },
    pricing: { currency: "USD", displayPrice: "Est. $3M+" },
    ticketUrl: "https://phillips.com",
    officialUrl: "https://phillips.com",
    tier: "premium",
    tags: ["Watches", "Phillips", "Luxury"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Phillips Geneva Watch Auction XVIII",
    description: "Important watches auction in Geneva",
    category: "auctions",
    subcategory: "Watches",
    startDate: new Date("2026-11-08"),
    location: { city: "Geneva", country: "Switzerland", venue: "Phillips Geneva" },
    pricing: { currency: "CHF", displayPrice: "Est. CHF 8M+" },
    ticketUrl: "https://phillips.com",
    officialUrl: "https://phillips.com",
    tier: "premium",
    tags: ["Watches", "Phillips", "Geneva"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Heritage Luxury Accessories",
    description: "Luxury handbags and accessories auction",
    category: "auctions",
    subcategory: "Accessories",
    startDate: new Date("2026-09-12"),
    location: { city: "Dallas", country: "USA", venue: "Heritage Auctions" },
    pricing: { currency: "USD", displayPrice: "Est. $1.5M+" },
    ticketUrl: "https://heritageauctions.com",
    officialUrl: "https://heritageauctions.com",
    tier: "premium",
    tags: ["Bags", "Hermès", "Luxury"],
    isActive: true,
    isFeatured: false
  },
  {
    title: "Heritage Fine Art & Antiques",
    description: "Fine art and antiques auction",
    category: "auctions",
    subcategory: "Art",
    startDate: new Date("2026-05-22"),
    location: { city: "New York", country: "USA", venue: "Heritage Auctions" },
    pricing: { currency: "USD", displayPrice: "Est. $4M+" },
    ticketUrl: "https://heritageauctions.com",
    officialUrl: "https://heritageauctions.com",
    tier: "premium",
    tags: ["Art", "Antiques", "Heritage"],
    isActive: true,
    isFeatured: false
  },
  {
    title: "Art Basel Hong Kong",
    description: "International art fair in Hong Kong",
    category: "arts",
    subcategory: "Art Fair",
    startDate: new Date("2027-03-25"),
    location: { city: "Hong Kong", country: "China", venue: "Hong Kong Convention Centre" },
    pricing: { currency: "USD", displayPrice: "$75-$500" },
    ticketUrl: "https://artbasel.com/hong-kong",
    officialUrl: "https://artbasel.com/hong-kong",
    tier: "free",
    tags: ["Art", "Contemporary", "Asia"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Art Basel Basel",
    description: "International art fair in Basel",
    category: "arts",
    subcategory: "Art Fair",
    startDate: new Date("2026-06-18"),
    location: { city: "Basel", country: "Switzerland", venue: "Messe Basel" },
    pricing: { currency: "USD", displayPrice: "$75-$500" },
    ticketUrl: "https://artbasel.com/basel",
    officialUrl: "https://artbasel.com/basel",
    tier: "free",
    tags: ["Art", "Contemporary", "Europe"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "TEFAF Maastricht",
    description: "The world's leading art fair",
    category: "arts",
    subcategory: "Art Fair",
    startDate: new Date("2027-03-12"),
    location: { city: "Maastricht", country: "Netherlands", venue: "MECC Maastricht" },
    pricing: { currency: "EUR", displayPrice: "EUR 50+" },
    ticketUrl: "https://tefaf.com",
    officialUrl: "https://tefaf.com",
    tier: "free",
    tags: ["Art", "Fine Art", "TEFAF"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "TEFAF New York",
    description: "TEFAF New York Spring/Fall",
    category: "arts",
    subcategory: "Art Fair",
    startDate: new Date("2026-05-06"),
    location: { city: "New York", country: "USA", venue: "Park Avenue Armory" },
    pricing: { currency: "USD", displayPrice: "$50+" },
    ticketUrl: "https://tefaf.com",
    officialUrl: "https://tefaf.com",
    tier: "free",
    tags: ["Art", "Fine Art", "New York"],
    isActive: true,
    isFeatured: false
  },
  {
    title: "Concours d'Elegance Pebble Beach",
    description: "Premier classic car show and competition",
    category: "experiences",
    subcategory: "Cars",
    startDate: new Date("2026-08-16"),
    location: { city: "Pebble Beach", country: "USA", venue: "Pebble Beach Golf Links" },
    pricing: { currency: "USD", displayPrice: "$750+" },
    ticketUrl: "https://pebblebeachconcours.net",
    officialUrl: "https://pebblebeachconcours.net",
    tier: "premium",
    tags: ["Cars", "Classic", "Concours"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Met Gala 2027",
    description: "Costume Institute Gala at The Met",
    category: "experiences",
    subcategory: "Fashion",
    startDate: new Date("2027-05-03"),
    location: { city: "New York", country: "USA", venue: "The Metropolitan Museum" },
    pricing: { currency: "USD", displayPrice: "$35K+" },
    ticketUrl: "#",
    officialUrl: "https://metmuseum.org/met-gala",
    tier: "premium",
    tags: ["Fashion", "Charity", "VIP"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Venice Biennale 2026",
    description: "International art exhibition",
    category: "arts",
    subcategory: "Art Exhibition",
    startDate: new Date("2026-04-18"),
    endDate: new Date("2026-11-22"),
    location: { city: "Venice", country: "Italy", venue: "Giardini and Arsenale" },
    pricing: { currency: "EUR", displayPrice: "EUR 25+" },
    ticketUrl: "https://labiennale.org",
    officialUrl: "https://labiennale.org",
    tier: "free",
    tags: ["Art", "Contemporary", "Venice"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Art Basel Paris",
    description: "International art fair in Paris",
    category: "arts",
    subcategory: "Art Fair",
    startDate: new Date("2026-10-16"),
    location: { city: "Paris", country: "France", venue: "Grand Palais" },
    pricing: { currency: "USD", displayPrice: "$75-$500" },
    ticketUrl: "https://artbasel.com/paris",
    officialUrl: "https://artbasel.com/paris",
    tier: "free",
    tags: ["Art", "Contemporary", "Paris"],
    isActive: true,
    isFeatured: false
  },
  {
    title: "Christie's Magnificent Jewels",
    description: "Magnificent jewels auction in New York",
    category: "auctions",
    subcategory: "Jewelry",
    startDate: new Date("2026-12-08"),
    location: { city: "New York", country: "USA", venue: "Christie's Rockefeller" },
    pricing: { currency: "USD", displayPrice: "Est. $8M+" },
    ticketUrl: "https://christies.com",
    officialUrl: "https://christies.com",
    tier: "premium",
    tags: ["Jewelry", "Diamonds", "Luxury"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Sotheby's Contemporary Evening NY",
    description: "Contemporary art evening auction in New York",
    category: "auctions",
    subcategory: "Art",
    startDate: new Date("2026-11-18"),
    location: { city: "New York", country: "USA", venue: "Sotheby's York Avenue" },
    pricing: { currency: "USD", displayPrice: "Est. $20M+" },
    ticketUrl: "https://sothebys.com",
    officialUrl: "https://sothebys.com",
    tier: "premium",
    tags: ["Art", "Contemporary", "New York"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "F1 Singapore Grand Prix",
    description: "Formula 1 night race in Singapore",
    category: "sports",
    subcategory: "F1",
    startDate: new Date("2026-10-04"),
    location: { city: "Singapore", country: "Singapore", venue: "Marina Bay Street Circuit" },
    pricing: { currency: "SGD", displayPrice: "S$1,500+" },
    ticketUrl: "https://singaporegp.sg",
    officialUrl: "https://singaporegp.sg",
    tier: "premium",
    tags: ["F1", "Night Race", "Singapore"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "F1 Abu Dhabi Grand Prix",
    description: "Formula 1 season finale at Yas Marina",
    category: "sports",
    subcategory: "F1",
    startDate: new Date("2026-12-06"),
    location: { city: "Yas Marina", country: "UAE", venue: "Yas Marina Circuit" },
    pricing: { currency: "AED", displayPrice: "AED 2,500+" },
    ticketUrl: "https://yasmarinacircuit.com",
    officialUrl: "https://yasmarinacircuit.com",
    tier: "premium",
    tags: ["F1", "Season Finale", "Abu Dhabi"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "F1 British Grand Prix",
    description: "Formula 1 at Silverstone Circuit",
    category: "sports",
    subcategory: "F1",
    startDate: new Date("2026-07-05"),
    location: { city: "Silverstone", country: "UK", venue: "Silverstone Circuit" },
    pricing: { currency: "GBP", displayPrice: "GBP 350+" },
    ticketUrl: "https://silverstone.co.uk",
    officialUrl: "https://silverstone.co.uk",
    tier: "premium",
    tags: ["F1", "Historic", "British"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "US Open Tennis Championships",
    description: "US Open Grand Slam tennis tournament",
    category: "sports",
    subcategory: "Tennis",
    startDate: new Date("2026-08-31"),
    endDate: new Date("2026-09-13"),
    location: { city: "New York", country: "USA", venue: "USTA Billie Jean King Center" },
    pricing: { currency: "USD", displayPrice: "$600+" },
    ticketUrl: "https://usopen.org",
    officialUrl: "https://usopen.org",
    tier: "premium",
    tags: ["Tennis", "Grand Slam", "New York"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Australian Open",
    description: "Australian Open Grand Slam tennis tournament",
    category: "sports",
    subcategory: "Tennis",
    startDate: new Date("2027-01-18"),
    endDate: new Date("2027-01-31"),
    location: { city: "Melbourne", country: "Australia", venue: "Melbourne Park" },
    pricing: { currency: "AUD", displayPrice: "AUD 500+" },
    ticketUrl: "https://ausopen.com",
    officialUrl: "https://ausopen.com",
    tier: "premium",
    tags: ["Tennis", "Grand Slam", "Australia"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "The Masters Tournament",
    description: "Golf's most prestigious major championship",
    category: "sports",
    subcategory: "Golf",
    startDate: new Date("2027-04-05"),
    location: { city: "Augusta", country: "USA", venue: "Augusta National Golf Club" },
    pricing: { currency: "USD", displayPrice: "$3,000+" },
    ticketUrl: "https://masters.com",
    officialUrl: "https://masters.com",
    tier: "premium",
    tags: ["Golf", "Major", "Augusta"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "The Open Championship",
    description: "The oldest golf major championship",
    category: "sports",
    subcategory: "Golf",
    startDate: new Date("2026-07-12"),
    location: { city: "St Andrews", country: "UK", venue: "Old Course at St Andrews" },
    pricing: { currency: "GBP", displayPrice: "GBP 250+" },
    ticketUrl: "https://theopen.com",
    officialUrl: "https://theopen.com",
    tier: "premium",
    tags: ["Golf", "Major", "St Andrews"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Winter Olympics 2026",
    description: "Milan-Cortina Winter Olympic Games",
    category: "sports",
    subcategory: "Olympics",
    startDate: new Date("2026-02-06"),
    endDate: new Date("2026-02-22"),
    location: { city: "Milan-Cortina", country: "Italy", venue: "Multiple Venues" },
    pricing: { currency: "EUR", displayPrice: "EUR 150+" },
    ticketUrl: "https://milanocortina2026.org",
    officialUrl: "https://milanocortina2026.org",
    tier: "premium",
    tags: ["Winter Olympics", "Italy", "Sports"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "FIFA World Cup 2026",
    description: "FIFA World Cup across USA, Canada, Mexico",
    category: "sports",
    subcategory: "Football",
    startDate: new Date("2026-06-11"),
    endDate: new Date("2026-07-19"),
    location: { city: "Multiple Cities", country: "USA/Canada/Mexico", venue: "Multiple Stadiums" },
    pricing: { currency: "USD", displayPrice: "$600+" },
    ticketUrl: "https://fifa.com/worldcup",
    officialUrl: "https://fifa.com/worldcup",
    tier: "premium",
    tags: ["Football", "World Cup", "FIFA"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Canelo vs Bivol II",
    description: "World championship boxing rematch",
    category: "sports",
    subcategory: "Boxing",
    startDate: new Date("2026-09-19"),
    location: { city: "Las Vegas", country: "USA", venue: "T-Mobile Arena" },
    pricing: { currency: "USD", displayPrice: "$1,200+" },
    ticketUrl: "#",
    officialUrl: "https://t-mobilearena.com",
    tier: "premium",
    tags: ["Boxing", "Title Fight", "Las Vegas"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Kentucky Derby",
    description: "The most exciting two minutes in sports",
    category: "sports",
    subcategory: "Horse Racing",
    startDate: new Date("2027-05-02"),
    location: { city: "Louisville", country: "USA", venue: "Churchill Downs" },
    pricing: { currency: "USD", displayPrice: "$2,000+" },
    ticketUrl: "https://kentuckyderby.com",
    officialUrl: "https://kentuckyderby.com",
    tier: "premium",
    tags: ["Horse Racing", "VIP", "Kentucky"],
    isActive: true,
    isFeatured: false
  },
  {
    title: "Royal Ascot",
    description: "Britain's most valuable race meeting",
    category: "sports",
    subcategory: "Horse Racing",
    startDate: new Date("2027-06-16"),
    location: { city: "Ascot", country: "UK", venue: "Ascot Racecourse" },
    pricing: { currency: "GBP", displayPrice: "GBP 500+" },
    ticketUrl: "https://ascot.co.uk",
    officialUrl: "https://ascot.co.uk",
    tier: "premium",
    tags: ["Horse Racing", "Royal", "UK"],
    isActive: true,
    isFeatured: false
  },
  {
    title: "Monaco Historic Grand Prix",
    description: "Historic Formula 1 cars race at Monaco",
    category: "sports",
    subcategory: "Motorsport",
    startDate: new Date("2027-05-10"),
    location: { city: "Monaco", country: "Monaco", venue: "Circuit de Monaco" },
    pricing: { currency: "EUR", displayPrice: "EUR 500+" },
    ticketUrl: "https://acm.mc",
    officialUrl: "https://acm.mc",
    tier: "premium",
    tags: ["Motorsport", "Historic", "Monaco"],
    isActive: true,
    isFeatured: false
  },
  {
    title: "Dubai International Boat Show",
    description: "Middle East's leading maritime event",
    category: "yachts",
    subcategory: "Superyachts",
    startDate: new Date("2027-03-10"),
    location: { city: "Dubai", country: "UAE", venue: "Dubai Harbour" },
    pricing: { currency: "AED", displayPrice: "AED 150+" },
    ticketUrl: "https://dubaiboatshow.com",
    officialUrl: "https://dubaiboatshow.com",
    tier: "premium",
    tags: ["Superyachts", "Middle East", "Dubai"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Fort Lauderdale Boat Show",
    description: "America's largest in-water boat show",
    category: "yachts",
    subcategory: "Superyachts",
    startDate: new Date("2026-10-28"),
    location: { city: "Fort Lauderdale", country: "USA", venue: "Bahia Mar Yachting Center" },
    pricing: { currency: "USD", displayPrice: "$150+" },
    ticketUrl: "https://flibs.com",
    officialUrl: "https://flibs.com",
    tier: "premium",
    tags: ["Superyachts", "Americas", "Florida"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Cannes Yachting Festival",
    description: "Europe's leading in-water boat show",
    category: "yachts",
    subcategory: "Superyachts",
    startDate: new Date("2026-09-08"),
    location: { city: "Cannes", country: "France", venue: "Vieux Port & Port Canto" },
    pricing: { currency: "EUR", displayPrice: "EUR 75+" },
    ticketUrl: "https://cannesyachtingfestival.com",
    officialUrl: "https://cannesyachtingfestival.com",
    tier: "premium",
    tags: ["Superyachts", "Mediterranean", "France"],
    isActive: true,
    isFeatured: true
  },
  {
    title: "Superyacht Miami",
    description: "Premier superyacht showcase in Miami",
    category: "yachts",
    subcategory: "Superyachts",
    startDate: new Date("2027-02-12"),
    location: { city: "Miami", country: "USA", venue: "Island Gardens" },
    pricing: { currency: "USD", displayPrice: "$250+" },
    ticketUrl: "https://superyachtmiami.com",
    officialUrl: "https://superyachtmiami.com",
    tier: "premium",
    tags: ["Superyachts", "Americas", "Miami"],
    isActive: true,
    isFeatured: false
  }
];

async function seedDatabase() {
  try {
    if (!process.env.MONGODB_URI) {
      console.error('ERROR: MONGODB_URI environment variable is not set');
      process.exit(1);
    }

    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing events
    console.log('Clearing existing events...');
    await Event.deleteMany({});
    console.log('Existing events cleared');

    // Insert new events
    console.log(`Inserting ${events.length} events...`);
    await Event.insertMany(events);
    console.log(`Successfully inserted ${events.length} events!`);

    // Verify
    const count = await Event.countDocuments();
    console.log(`Total events in database: ${count}`);

    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seedDatabase();
